name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm i
      - run: npm run test:ember
      - run: npm run lint:js
      - run: npm run lint:hbs
      - run: npm run build
      - name: release
        uses: softprops/action-gh-release@v1
        id: startsWith(github.ref, 'refs/tags/')
        with:
          files: README.md
